name: arc_progress_bar_new
description: Generally a Curved/arc Progress Bar package
version: 1.0.2
homepage: https://github.com/Frankline-Sable/arc_progress_bar

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

